### ISSUE TITLE
cannot open KCV in windows 10

### ISSUE THREAD

**Issue by coblade14** [Grabacr07/KanColleViewer#157]
ERROR, date = 2015-08-10 6:26:38 PM -07:00, sender = System.Windows.Threading.Dispatcher,
System.IO.FileLoadException: Could not load file or assembly 'Counter, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'Counter, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.LoadAssembly(String codeBase)
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog..ctor(String codeBase)
   at Grabacr07.KanColleViewer.Composition.PluginService.Initialize()
   at Grabacr07.KanColleViewer.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<_ctor>b__0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Grabacr07** [comment]
![ss150811105523](https://cloud.githubusercontent.com/assets/1779073/9188474/807f3fa0-4017-11e5-9c0d-38dc8541c2e7.png)
